package dev.joss.dagger.cucumber.api;

/**
 * Bridge between the Dagger component graph and the Cucumber object-factory lifecycle.
 *
 * <p>An implementation is generated by {@code cucumber-dagger-processor} for every root component
 * annotated with {@link CucumberDaggerConfiguration}. The generated class is loaded by the runtime
 * at startup; user code does not implement or reference this interface directly.
 */
public interface ComponentResolver {

  /**
   * Creates a fresh per-scenario subcomponent from the root component.
   *
   * @param root the root Dagger component for the test run
   * @return a new {@link ScenarioScopedComponent} instance for the current scenario
   */
  ScenarioScopedComponent createScoped(CucumberDaggerComponent root);

  /**
   * Resolves {@code type} from the per-scenario subcomponent, or {@code null} if the type is not
   * provided by the scoped component.
   *
   * @param type the class to resolve
   * @param scoped the per-scenario subcomponent for the current scenario
   * @return the instance, or {@code null} if not found
   */
  Object resolveScoped(Class<?> type, ScenarioScopedComponent scoped);

  /**
   * Resolves {@code type} from the root component, or {@code null} if the type is not provided by
   * the root component.
   *
   * @param type the class to resolve
   * @param root the root Dagger component for the test run
   * @return the instance, or {@code null} if not found
   */
  Object resolveRoot(Class<?> type, CucumberDaggerComponent root);
}
